### PR TITLE
ENH: add PVS for flow, press on MR2K4

### PR DESCRIPTION
**Pull request by nrwslac**
Added 2 flow sensors and 1 pressure sensor.

### CODE REVIEW

**Review by klauer — APPROVED** [review]
I didn't scrutinize the xti changes, but the code changes + pragmas seem fine. IOC rebuild of course is in order to get the new PVs.

**Review by ZLLentz — COMMENTED** [review]
The change looks like it will work cleanly, but I don't think the PVs this produces will be useful. They are going to be uninterpretable 12 to 16-bit integers cast as floats.

You probably will want to rescale these based on the specs from your sensors. We have some function blocks in the general library for this purpose: https://github.com/pcdshub/lcls-twincat-general/blob/master/LCLSGeneral/LCLSGeneral/POUs/Hardware/FB_AnalogInput.TcPOU, or you can roll your own.

**Comment by ZLLentz** [comment]
FYI I'm pretty sure the units here are incorrect- you are missing an important scaling factor to do the full conversion:
[0, 2^12] integer -> [4mA, 20mA] flowmeter -> real units

**Comment by ZLLentz** [comment]
Is there a way to scale the units in EPICS without adding additional CALC records? If you're doing that somewhere, you can disregard me. But the raw number you're getting from the terminal IO is definitely not in units of GPH or bar, which is how the PVs are labelled. Typically we'd scale the raw number in the plc to a real unit for the pragma'd PV.

**Comment by nrwslac** [comment]
I could be totally off here but I think if the sensor/ADU relationship is linear you can use:
LINR set to SLOPE, ASLO and AOFF

[env sensor calcs tab 3054](https://docs.google.com/spreadsheets/d/1IJFUcMpB-xMx_O1AfZxj1tH0Rarg73pIPnQpW-g4xrY/edit#gid=1445512046)

**Comment by ZLLentz** [comment]
I didn't know about that. If those are autosaved then you're probably good to go.
I'm not convinced that this is the best way to handle it (while in the PLC these numbers will be meaningless) but if it works, it works.

**Comment by ghalym** [comment]
I have the same question as Zach? The PLC doesn’t need to know these values? Doesn’t the PLC need to fault if the optics get too hot or the flow is less than a certain threshold?

**Comment by klauer** [comment]
Pragmas can be used to automatically set scale/offset: https://pcdshub.github.io/pytmc/v2.9.1/pragma_usage.html#scale-and-offset

**Comment by nrwslac** [comment]
I think we should put this on the PLC level. Seems more robust.

**Comment by nrwslac** [comment]
> I have the same question as Zach? The PLC doesn’t need to know these values? Doesn’t the PLC need to fault if the optics get too hot or the flow is less than a certain threshold?

also this

**Pull request merged**
