### PR TITLE
BLD: LCLS-General 2.7.0 -> 2.8.1

### PR DESCRIPTION
**Pull request by nrwslac**
## Description

LCLS-General 2.7.0 -> 2.8.1
## Motivation and Context

Found Pytmc error when building IOC.
```
    ERROR:pytmc.bin.db:Duplicate records encountered: 
    $(PREFIX)LCLSGeneral:GlobalLogTrickleTrip_RBV (2)
    $(PREFIX)LCLSGeneral:LogHost (2)
    $(PREFIX)LCLSGeneral:LogHost_RBV (2)
    $(PREFIX)LCLSGeneral:LogMessageCount_RBV (2)
    $(PREFIX)LCLSGeneral:LogPort (2)
    $(PREFIX)LCLSGeneral:LogPort_RBV (2)
```

## How Has This Been Tested?

Rebuilt the IOC without error.

## Pre-merge checklist
- [x] Code works interactively
- [x] Code contains descriptive comments
- [x] Test suite passes locally
- [x] Libraries are set to fixed versions and not ``Always Newest``
- [x] Code committed with ``pre-commit`` (alternatively ``pre-commit run --all-files``)

### CODE REVIEW

**Comment by ZLLentz** [comment]
I'm going to unassign myself and put myself as a reviewer instead, unless you're asking me to take over and complete the PR

**Review by ZLLentz — COMMENTED** [review]
I don't see any problem with this, but I'm concerned that you needed to do this. Is there something wrong with one of our libraries?

I'm worried that this will happen to everyone every time we update any library...

**Comment by nrwslac** [comment]
> I'm going to unassign myself and put myself as a reviewer instead, unless you're asking me to take over and complete the PR

Whoops, I thought I requested review.

**Comment by nrwslac** [comment]
> I don't see any problem with this, but I'm concerned that you needed to do this. Is there something wrong with one of our libraries?
> 
> I'm worried that this will happen to everyone every time we update any library...

I am not sure why this happens. I've seen this happen to others and myself with the same duplicated PV errors. I've only seen it happen with LCLS General, and when the project has mismatched LCLS General versions. It seems to not get noticed until one tries to build the IOC, as the PLC doesn't have conflicts with the two different versions of LCLS General when building.

**Comment by klauer** [comment]
> I am not sure why this happens. I've seen this happen to others and myself with the same duplicated PV errors. I've only seen it happen with LCLS General, and when the project has mismatched LCLS General versions. It seems to not get noticed until one tries to build the IOC, as the PLC doesn't have conflicts with the two different versions of LCLS General when building.

Yes, this is the place I've seen it, too. It used to be very common (common enough to be documented here: https://confluence.slac.stanford.edu/display/PCDS/Beckhoff+Flight+Rules#BeckhoffFlightRules-pytmcreports%22duplicaterecords%22), but less so nowadays with better pinning practices in our libraries.

This is another reason it's very important to include IOC updates in PRs so these sorts of issues can be caught early.

**Comment by nrwslac** [comment]
I guess there is nothing to do here then: a case of mismatched libraries; resolved.

**Comment by nrwslac** [comment]
> @nrwslac would you mind rebuilding the IOC and committing the changes to show that the library upgrade worked as you say?

Done. IOC builds without error. Aside, I don't why pre-commit style passes locally, fails online?

**Comment by ZLLentz** [comment]
It looks like "pre-commit" passes on both, but the specific "style check" segments fail online. Bizarre, I'll take a closer look.

**Comment by ZLLentz** [comment]
The style checks aren't running correctly, something might be configured weird?
```
Run cat "$HOME/project_files.txt" \
  cat "$HOME/project_files.txt" \
    | egrep --null-data --null --ignore-case -e $"\.TcPOU$" -e $"\.TcDUT$" -e $"\.TcGVL$" \
    | egrep --null-data --null --invert-match -e "${STYLE_EXCLUDE:=__unset__}" \
    > "$HOME/files_to_check.txt"
  shell: /usr/bin/bash --login -o pipefail {0}
  env:
    STYLE_EXCLUDE: 
Error: Process completed with exit code 1.
```

**Comment by klauer** [comment]
I have some fixes to do on the CI end of things - it's not your fault: https://github.com/pcdshub/pcds-ci-helpers/issues/110

**Comment by nrwslac** [comment]
> I have some fixes to do on the CI end of things - it's not your fault: [pcdshub/pcds-ci-helpers#110](https://github.com/pcdshub/pcds-ci-helpers/issues/110)

Sgtm! thank you.

**Pull request merged**
